const crypto=require('crypto');const bcrypt=require('bcryptjs');const {sql,ensureSchema}=require('./db');
const COOKIE='campaign_session';
function hashToken(token){return crypto.createHash('sha256').update(token).digest('hex')}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(v=>{const i=v.indexOf('=');return [v.slice(0,i).trim(),decodeURIComponent(v.slice(i+1))]}))}
async function bootstrapManager(){await ensureSchema();const username=process.env.CAMPAIGN_MANAGER_USERNAME;const password=process.env.CAMPAIGN_MANAGER_PASSWORD;if(!username||!password)return;const q=sql();const existing=await q`SELECT id FROM campaign_employees WHERE username=${username.toLowerCase()} LIMIT 1`;if(!existing.length){const hash=await bcrypt.hash(password,12);await q`INSERT INTO campaign_employees (username,display_name,password_hash,role) VALUES (${username.toLowerCase()},${process.env.CAMPAIGN_MANAGER_NAME||'Leiter der Parteizentrale'},${hash},'manager')`}}
async function getUser(req){await bootstrapManager();const token=cookies(req)[COOKIE];if(!token)return null;const q=sql();const rows=await q`SELECT e.id,e.username,e.display_name,e.role,e.active FROM campaign_sessions s JOIN campaign_employees e ON e.id=s.employee_id WHERE s.token_hash=${hashToken(token)} AND s.expires_at>NOW() AND e.active=TRUE LIMIT 1`;return rows[0]||null}
async function requireUser(req,res,role){const user=await getUser(req);if(!user){res.status(401).json({error:'Nicht angemeldet.'});return null}if(role&&user.role!==role){res.status(403).json({error:'Keine Berechtigung.'});return null}return user}
function setSessionCookie(res,token){const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`${COOKIE}=${encodeURIComponent(token)}; Path=/; HttpOnly; SameSite=Strict; Max-Age=28800${secure}`)}
function clearSessionCookie(res){const secure=process.env.NODE_ENV==='production'?'; Secure':'';res.setHeader('Set-Cookie',`${COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0${secure}`)}
module.exports={bcrypt,sql,ensureSchema,bootstrapManager,getUser,requireUser,hashToken,setSessionCookie,clearSessionCookie,COOKIE,cookies};
